Attēlu augšupielāde un faila nosaukuma glabāšana datubāzē
stwebcode/register pull request #14
Opened 2021-02-14 11:33 UTC by Filipssh

Noteikti vajag iztestēt pirms merge.
Croppie atbalsta JPEG/PNG/WEBP, ja izdodās kaut ko citu dabūt cauri, tad sakat.
Var augšupielādēt vairākus bildes izmērus, tik jāpieliek `cropImage()` funkcijai vēlviens `vanilla.result()` bloks.

+ pievienoju image kolonnu users tabulai
``ALTER TABLE `users` ADD `image` VARCHAR(20) NOT NULL AFTER `joined`;``
* pārbaudiet, vai `joined` kolonnai ir defaultā `CURRENT_TIMESTAMP`
``ALTER TABLE `users` CHANGE `joined` `joined` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;``

2021-02-14 19:52 UTC, CracX requested changes
Okay, ideja ir laba bet implementācijā ir dažas nepilnības.

Sāksim ar to, ka bilde vai jebkāds fails (par šo es parunāšu drusku vēlāk) tiek saglabāts pirms lietotāja dati tiek verificēti. Tas nozīmē, ka uzbrucējs var publicēt failus bez reģistrācijas. Es varu izveidot pieprasījumu serverim reģistrācijai ar jau reģistrētu nickname un pirmais ko tas darīs ir saglabās bildi un tikai tad verificēs vai es esmu valid cilvēks. Tas var arī pārpildīt storage ja klients ievada netīšām jau eksistējošu nickname, jo serveris, pēc pašreizējas konfigurācijas, vienmēr saglabās nosūtīto failu.

Nobeigšu ar to, ka es esmu atradis iespēju augšupielādēt failus, kas nav bildes, tomēr pagaidām nav izdevies publicēt pilnu php failu. Turpināšu testēt, bet pagaidām merging es neatbalstu.

2021-02-15 12:20 UTC, Filipssh commented
Tagad bildi augšupielādē pēc username un password pārbaudēm. Dēļ mime content type pārbaudēm man šķiet ka nevar uploadot arbitrary code, ja nu vienīgi kaut kā var spoofot png failu, bet tajā pašā laikā saglabāt kā php.
I'm not a haxor, bet tuvākais ko es varēju dabūt cauri ir broken png.

2021-02-15 12:38 UTC, CracX approved these changes
Jap, viss strādā! Par to failu mime tipa pārbaudi - vajadzēs pielietot whitelisting. Pagaidām šis risinājums ir strādājošs un drošs.

EDIT: MIME tipa whitelisting vajag lai, kad klients pieprasa šo non-whitelisted failu, nebūtu XSS uzbrukumi dēļ publicētiem html failiem vai x-html.

2021-02-15 13:12 UTC, janiszakis03 approved these changes
Nice!

2021-02-15 13:39 UTC, merged