evo-calendar implementācija
stwebcode/register pull request #20
Opened 2021-03-05 14:12 UTC by Filipssh

pievienoju `events` tabulu, no kuras populē kalendāru.
ir arī opcija pievienot event ar kontu, kuram piešķirts `roleID` kā skolotājs.
event veidlapa ir subject to change.
datu validācija vēl ir iffy.
event pievienošanas funkcijas nepieejamība skolēniem vel nav pārbaudīta.

taisu pull request tagad, lai būtu ko parādīt kad vadība gribēs redzēt progresu.

2021-03-05 14:58 UTC, CracX requested changes
Funkcionalitātes ziņā viss strādā. Tomēr ir daži drošības riski, kā jau tu minēji.

2021-03-05 14:58 UTC, CracX commented on server.php
> +if($_POST['action'] == "insert_event"){
Noteikti vajadzētu verificēt vai:

1. Klientam, kas pieprasa šo ir izveidota aktīva sesija,
2. klients ir skolotājs.

Pēc principa, es kā hakeris varu vienkārši izveidot pieprasījumu serverim kā neautentificējies skolēns un šo pieprasījumu serveris apstrādātu bez kļūdām. Noteikti security risks.

2021-03-07 18:38 UTC, Filipssh commented
es izveidoju `event_colors` tabulu, līdz ar to dzēsu `color` kolonnu no `events` tabulas.
sekojoši radīju `events_out` "VIEW", kurā tiek piešķirtas krāsas atkarībā no event type. Šādā veidā lietotājs var ievadīt savu event type, kuram datubāze iedalīs default krāsu, vai arī atlasīt vienu no `<datalist>` piedāvātajiem type, kuriem piešķirtas speciālas krāsas.

2021-03-08 09:02 UTC, janiszakis03 commented
Viss strādā! Par drošību nezinu, jo to daudz nesaprotu, bet funkcionalitātes ziņā viss darbojas. Vienīgais, uz mana ekrāna, kad uzslēdz februāri, tad to pogu "+ Jauns ieraksts" pusi tikai var redzēt. Es domāju, ka vislabāk būtu, ja kalendāra izmērs nemainītos, kad pārslēdz mēnešus, kuros ir vairāk vai mazāk dienu. Bet tās ir tikai manas domas.

2021-03-08 10:40 UTC, Filipssh commented
> 
> 
> Viss strādā! Par drošību nezinu, jo to daudz nesaprotu, bet funkcionalitātes ziņā viss darbojas. Vienīgais, uz mana ekrāna, kad uzslēdz februāri, tad to pogu "+ Jauns ieraksts" pusi tikai var redzēt. Es domāju, ka vislabāk būtu, ja kalendāra izmērs nemainītos, kad pārslēdz mēnešus, kuros ir vairāk vai mazāk dienu. Bet tās ir tikai manas domas.

šis laikam ir veidots pirms tāda lieta kā grid eksistēja. tur viss ir uz position:absolute Pagaidām nevaru noteikt cik daudz css būtu jāpārraksta tikai lai kalendāra augstumu varētu jēdzīgi pārmainīt.

2021-03-09 10:56 UTC, CracX approved these changes

2021-03-09 10:56 UTC, CracX commented
Pagaidām viss izskatās ok drošības ziņā. Pēc pull noteikti vēl dziļāk patestēšu aplikāciju

2021-03-09 11:14 UTC, jay3871 approved these changes

2021-03-12 08:45 UTC, merged